replicaCount: 1

image:
  repository: langfuse/langfuse
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

langfuse:
  port: 3000
  nodeEnv: production
  next:
    healthcheckBasePath: ""
  nextauth:
    url: http://localhost:3000
    secret: changeme
  salt: changeme
  telemetryEnabled: True
  nextPublicSignUpDisabled: False
  enableExperimentalFeatures: True
  extraContainers: []
  extraVolumes: []
  extraInitContainers: []
  extraVolumeMounts: []
  additionalEnv:
    - name: "LANGFUSE_LOG_FORMAT"
      value: "json"
    # Experimental v3 feature flags
    - name: "LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES"
      value: "true"
    - name: "LANGFUSE_ASYNC_INGESTION_PROCESSING"
      value: "true"
    - name: "LANGFUSE_ASYNC_CLICKHOUSE_INGESTION_PROCESSING"
      value: "true"
    - name: "LANGFUSE_READ_DASHBOARDS_FROM_CLICKHOUSE"
      value: "true"
    - name: "LANGFUSE_READ_FROM_POSTGRES_ONLY"
      value: "false"
    - name: "LANGFUSE_RETURN_FROM_CLICKHOUSE"
      value: "true"
    # REDIS
    - name: "REDIS_CONNECTION_STRING"
      value: "redis://default:changeme@langfuse-valkey-master:6379/0"
    # CLICKHOUSE
    - name: "CLICKHOUSE_MIGRATION_URL"
      value: "clickhouse://langfuse-clickhouse:9000"
    - name: "CLICKHOUSE_URL"
      value: "http://langfuse-clickhouse:8123"
    - name: "CLICKHOUSE_USER"
      value: "default"
    - name: "CLICKHOUSE_PASSWORD"
      value: "changeme"
    # S3 / MinIO
    - name: "LANGFUSE_S3_EVENT_UPLOAD_ENABLED"
      value: "true"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_BUCKET"
      value: "langfuse"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_REGION"
      value: "us-east-1"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID"
      value: "minio"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY"
      value: "miniosecret"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT"
      value: "http://langfuse-minio:9000"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE"
      value: "true"
    # example
    # - name: "DATABASE_PASSWORD"
    #   valueFrom:
    #     secretKeyRef:
    #       name: "my-secrets"
    #       key: "database-password"
    # - name: "EMAIL_FROM_ADDRESS"
    #   valueFrom:
    #     configMapKeyRef:
    #       name: "my-configmap"
    #       key: "email-from-address"
    # - name: DATABASE_USERNAME
    #   value: langfuse-postgres  

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  host: langfuse-postgresql
  auth:
    username: postgres
    password: postgres
    database: postgres_langfuse
  deploy: true
  architecture: standalone
  primary:
    service:
      ports:
        postgresql: 5432

clickhouse:
  deploy: true
  # Please do not change, as Langfuse v3 currently doesn't support Clickhouse clusters.
  shards: 1
  replicaCount: 1
  resourcesPreset: large
  auth:
    username: default
    password: changeme

valkey:
  deploy: true
  architecture: standalone
  primary:
    extraFlags:
      - "--maxmemory-policy noeviction"
  auth:
    password: changeme

minio:
  deploy: true
  defaultBuckets: 'langfuse'
  auth:
    rootUser: 'minio'
    rootPassword: 'miniosecret'

extraManifests: []
