replicaCount: 1

image:
  repository: langfuse/langfuse
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

langfuse:
  port: 3000
  nodeEnv: production
  nextauth:
    url: http://localhost:3000
    secret: changeme
  salt: changeme
  telemetryEnabled: True
  nextPublicSignUpDisabled: False
  enableExperimentalFeatures: True
  extraContainers: []
  extraVolumes: []
  extraInitContainers: []
  extraVolumeMounts: []
  additionalEnv:
    - name: "REDIS_CONNECTION_STRING"
      value: "redis://default:changeme@langfuse-valkey-master:6379/0"
    - name: "LANGFUSE_ASYNC_INGESTION_PROCESSING"
      value: "true"
    - name: "LANGFUSE_LOG_FORMAT"
      value: "json"
    # example
    # - name: "DATABASE_PASSWORD"
    #   valueFrom:
    #     secretKeyRef:
    #       name: "my-secrets"
    #       key: "database-password"
    # - name: "EMAIL_FROM_ADDRESS"
    #   valueFrom:
    #     configMapKeyRef:
    #       name: "my-configmap"
    #       key: "email-from-address"
    # - name: DATABASE_USERNAME
    #   value: langfuse-postgres  

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  auth:
    username: postgres
    password: postgres
    database: postgres_langfuse
  deploy: true
  architecture: standalone
  primary:
    service:
      ports:
        postgresql: 5432

clickhouse:
  deploy: true
  auth:
    username: default
    password: changeme

valkey:
  deploy: true
  architecture: standalone
  primary:
    extraFlags:
      - "--maxmemory-policy noeviction"
  auth:
    password: changeme

extraManifests: []
